OUTPUT = ../../gen/output

all:$(OUTPUT)/summary_stats.csv $(OUTPUT)/meanplot_pricedif_district.pdf $(OUTPUT)/boxplot_pricedif_district_filtered.pdf $(OUTPUT)/only_price_district.aov $(OUTPUT)/tukey.plot.aov.csv $(OUTPUT)/tukey.plot.test.pdf 

$(OUTPUT)/meanplot_pricedif_district.pdf: Analysis.R
	R --vanilla < Analysis.R
	
$(OUTPUT)/summary_stats.csv:

$(OUTPUT)/boxplot_pricedif_district_filtered.pdf:

$(OUTPUT)/only_price_district.aov:

$(OUTPUT)/tukey.plot.aov.csv: 

$(OUTPUT)/tukey.plot.test.pdf:



