TEMP = ../../gen/temp
OUTPUT = ../../gen/output

all: $(TEMP)/only_price_district.csv $(OUTPUT)/summary_stats.csv $(OUTPUT)/meanplot_pricedif_district.pdf $(OUTPUT)/boxplot_pricedif_district_filtered.pdf $(OUTPUT)/leveneTest.csv $(OUTPUT)/only_price_district.aov $(OUTPUT)/eta_squared.csv $(OUTPUT)/tukey.plot.aov.csv $(OUTPUT)/tukey.plot.test.pdf 

$(TEMP)/only_price_district.csv: Analysis.R
	R --vanilla < Analysis.R

$(OUTPUT)/summary_stats.csv:

$(OUTPUT)/meanplot_pricedif_district.pdf:

$(OUTPUT)/boxplot_pricedif_district_filtered.pdf:

$(OUTPUT)/leveneTest.csv:

$(OUTPUT)/only_price_district.aov:

$(OUTPUT)/eta_squared.csv:

$(OUTPUT)/tukey.plot.aov.csv: 

$(OUTPUT)/tukey.plot.test.pdf:



